apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorsdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      color: blue
      demo: colorsdemo
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        color: blue
        demo: colorsdemo
    spec:
      containers:
        - name: blue
          image: denniszielke/blue:latest
          ports:
          - containerPort: 80
            name: http
            protocol: TCP 
