apiVersion: v1
kind: Service
metadata:
  name: blue-svc
  labels:
    color: blue
    demo: colorsdemo
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  type: LoadBalancer
  selector:
    color: blue
    demo: colorsdemo