{{- if .Values.dependencies.useAppInsights }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multicalculator.fullname" . }}-appin-secret
type: Opaque
data:
  appinsightskey: {{ .Values.dependencies.appInsightsSecretValue | b64enc }}
{{- end }}
---
{{- if .Values.dependencies.useAzureRedis }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multicalculator.fullname" . }}-redis-secret
type: Opaque
data:
  redishostkey: {{ .Values.dependencies.redisHostValue | b64enc }}
  redisauthkey: {{ .Values.dependencies.redisKeyValue | b64enc }}
{{- end }}